# Generated by Django 3.2.8 on 2021-12-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myId', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('percipitation', models.FloatField()),
            ],
        ),
    ]
